apiVersion: 1

datasources:
  - name: InfluxDB_v2_SpacePoint
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: ruya_spacepoint
      defaultBucket: cubesat_telemetry
    secureJsonData:
      token: ruya_super_secret_token_2026
