[agent]
  interval = "1s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "1s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = [
    "spacepoint/telemetry/json"
  ]
  data_format = "json"
  tag_keys = ["flight_mode", "anomaly_flags"]
  json_string_fields = ["sync_word"]
  name_override = "cubesat_telemetry"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "ruya_super_secret_token_2026"
  organization = "ruya_spacepoint"
  bucket = "cubesat_telemetry"
